/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:71e0f82b-2ea7-4ea3-8be3-d21b35e7fa4b",
    "aws_cognito_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sla2nph3orgjbccyqrv6bfhmfa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_authenticationType": "API_KEY",
    aws_appsync_apiKey: 'da2-ln6qec5rqramrlpfpm7uiuz64i',
    "aws_user_pools_id": "us-east-1_oyDOhnVf6",
    "aws_user_pools_web_client_id": "1noi46dbud0satg6boijf7o0tn",
    "oauth": {
        "domain": "abrehet014c7ce4-014c7ce4-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "abrehet://,http://localhost:3000/,https://mesobstore.com/",
        "redirectSignOut": "abrehet://,http://localhost:3000/,https://mesobstore.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
