projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: us-east-1
        apiId: 7tqahdabdndl7mhgoxdx7ytzeq
        frontend: javascript
        framework: react
        maxDepth: 2
